[package]
name = "tempfiles-rs"
version = "0.1.0"
authors = ["Edwin Svensson <tempfilesrs@olback.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4"
rocket_contrib = { version = "0.4", default-features = false, features = [ "handlebars_templates", "serve", "json" ] }
rand = "0.7"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
# https://github.com/RustCrypto/AEADs
