[package]
name = "tempfiles-rs"
version = "0.1.0"
authors = ["Edwin Svensson <tempfilesrs@olback.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4"
rand = "0.7"
# https://github.com/RustCrypto/AEADs
