version: '3.1'

services:

  postgres:
    image: olback/postgres12-pg-cron:2020-06-01
    command: "-c shared_preload_libraries='pg_cron' -c cron.database_name='${POSTGRES_USER}'"
    restart: unless-stopped
    # ports:
    #   - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./scripts/postgres:/scripts/

  server:
    image: registry.olback.dev/olback/tempfiles-rs
    restart: unless-stopped
    tty: true
    depends_on:
      - postgres
    ports:
      - "${ROCKET_PORT}:${ROCKET_PORT}"
    environment:
      ROCKET_ADDRESS: ${ROCKET_ADDRESS}
      ROCKET_PORT: ${ROCKET_PORT}
      ROCKET_WORKERS: ${ROCKET_WORKERS}
      ROCKET_LOG_LEVEL: ${ROCKET_LOG_LEVEL}
      ROCKET_LIMITS: "{forms=${ROCKET_LIMITS_FORMS}, bytes=${ROCKET_LIMITS_BYTES}}"
      ROCKET_DATABASES: "{tempfiles={url=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}?sslmode=${POSTGRES_SSLMODE},tls={ssl_root_cert=${POSTGRES_CA}}}}"
      ROCKET_LIMITS_BYTES: ${ROCKET_LIMITS_BYTES}
      TEMPFILES_BASE_URL: ${TEMPFILES_BASE_URL}
      TEMPFILES_NAME: ${TEMPFILES_NAME}
      #TEMPFILES_KEEP_HOURS: ${TEMPFILES_KEEP_HOURS}
      #TEMPFILES_CLEANUP_INTERVAL: ${TEMPFILES_CLEANUP_INTERVAL}
      #TEMPFILES_CLEANUP_KEY: ${TEMPFILES_CLEANUP_KEY}
