version: '3.1'

services:

  postgres:
    image: olback/postgres12-pg-cron:latest
    command: "-c shared_preload_libraries='pg_cron' -c cron.database_name='${POSTGRES_USER}'"
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./scripts/postgres:/scripts/

  # server:
  #   image: alpine
  #   restart: unless-stopped
  #   command: /tempfiles/scripts/entrypoint.sh
  #   tty: true
  #   ports:
  #     - "${ROCKET_PORT}:${ROCKET_PORT}"
  #   environment:
  #     ROCKET_ENV: ${ENV}
  #     ROCKET_ADDRESS: ${ROCKET_ADDRESS}
  #     ROCKET_PORT: ${ROCKET_PORT}
  #     ROCKET_WORKERS: ${ROCKET_WORKERS}
  #     ROCKET_LOG: ${ROCKET_LOG}
  #     ROCKET_LIMITS: "{forms=${ROCKET_LIMITS_FORMS}, files=${LIMITS_FILES}}"
  #     ROCKET_DATABASES: "{tempfiles={url=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_USER}}}"
  #     ROCKET_BASE_URL: ${BASE_URL}
  #     ROCKET_NAME: ${NAME}
  #   volumes:
  #     - "./assets:/tempfiles/assets"
  #     - "./scripts/server:/tempfiles/scripts"
  #     - "./target/x86_64-unknown-linux-musl:/tempfiles/target"
  #     - "./templates:/tempfiles/templates"
