# This file is only used during development!
# Production uses environment variables

[development]
address = "0.0.0.0"
port = 5000
workers = 8
log = "normal"
limits = { forms = 32768, files = 26214400 }
base_url = "http://192.168.0.129:5000"
databases = { tempfiles = { url = "postgresql://tempfiles:tempfiles@localhost:5432/tempfiles" } }
name = "Tempfiles"

[staging]
address = "0.0.0.0"
port = 5000
workers = 8
log = "normal"
limits = { forms = 32768, files = 26214400 }

[production]
address = "0.0.0.0"
port = 5000
workers = 2
log = "critical"
limits = { forms = 32768, files = 26214400 }
