[development]
address = "0.0.0.0"
port = 5000
workers = 8
# log = "debug"
log = "normal"
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 5000
workers = 8
log = "normal"
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 3000
workers = 2
log = "critical"
limits = { forms = 32768 }
